In [2]:
import pandas as pd
dfa = pd.read_csv('Labor_force_participation_rate_ female.csv',encoding="GBK")
dfa

,country,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,42.709000,42.735001,43.327999,44.117001,45.039001,46.016998,47.000999,47.765999,48.473999,48.660000,48.848999
2,Angola,75.255997,75.306999,75.344002,75.389000,75.432999,75.464996,75.478996,75.470001,75.450996,75.412003,75.372002
3,Albania,44.945000,45.693001,47.104000,48.806000,44.650002,44.789001,47.675999,47.459000,47.312000,47.191002,47.081001
4,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Arab World,20.052651,20.169026,20.268955,20.453085,20.753035,20.686165,20.492409,20.589288,20.536024,20.537448,20.525228
6,United Arab Emirates,42.514999,44.028999,45.143002,46.213001,47.263000,48.323002,49.396000,50.161999,51.266998,51.148998,51.067001
7,Argentina,48.823002,47.833000,48.102001,48.188000,47.790001,47.157001,47.825001,48.480000,49.118000,48.966999,48.813999
8,Armenia,48.299000,49.587002,52.091999,51.969002,52.631001,51.946999,51.166000,49.441002,49.419998,49.575001,49.674000
9,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Australia,58.821999,58.706001,58.952000,58.826000,58.707001,58.648998,59.066002,59.247002,59.693001,59.645000,59.591000
12,Austria,53.373001,53.507000,53.839001,54.337002,54.598999,54.562000,54.535999,54.945999,54.868999,54.826000,54.745998
13,Azerbaijan,59.617001,60.223000,60.813999,61.104000,61.323002,61.923000,62.516998,62.963001,63.262001,63.112999,62.916000
14,Burundi,80.610001,80.349998,80.112000,79.917999,79.748001,79.573998,79.844002,80.079002,80.286003,80.348999,80.363998
15,Belgium,46.745998,47.488998,46.805000,46.889000,47.594002,48.011002,48.023998,47.765999,47.891998,47.889000,47.867001
16,Benin,68.933998,69.223999,68.088997,68.207001,68.351997,68.512001,68.680000,68.835999,69.016998,69.176002,69.334999
17,Burkina Faso,60.092999,59.717999,59.341000,58.971001,58.606998,58.249001,58.375999,58.497002,58.626999,58.462002,58.292000
18,Bangladesh,29.382000,29.882999,30.371000,30.864000,31.364000,31.871000,32.383999,32.889999,35.852001,35.999001,36.143002
19,Bulgaria,48.089001,47.698002,47.216999,47.825001,48.528000,48.629002,48.632999,47.764999,49.626999,49.529999,49.416000
20,Bahrain,42.604000,43.763000,43.004002,43.202999,43.404999,43.615002,43.800999,44.011002,44.352001,44.473000,44.612999
21,"Bahamas, The",68.639999,68.742996,68.555000,68.616997,68.436996,68.180000,67.744003,67.530998,67.527000,67.568001,67.540001
22,Bosnia and Herzegovina,37.223999,37.063999,36.837002,36.547001,36.273998,35.972000,35.667000,35.258999,35.726002,35.627998,35.521000
23,Belarus,57.152000,57.540001,57.861000,58.136002,58.358002,58.527000,58.641998,58.665001,58.395000,58.126999,57.827000
24,Belize,50.747002,51.938000,53.235001,54.527000,53.701000,52.930000,52.212002,52.768002,52.924999,53.280998,53.648998
25,Bermuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Bolivia,62.367001,62.019001,61.651001,57.944000,58.820999,60.900002,54.508999,60.321999,56.585999,56.595001,56.611000
27,Brazil,54.966000,53.576000,52.173000,53.077999,52.976002,52.860001,53.377998,53.320999,54.167999,54.029999,53.882000
28,Barbados,63.606998,63.492001,63.287998,62.061001,63.230999,61.855999,61.860001,62.568001,62.234001,61.894001,61.528000
29,Brunei Darussalam,56.659000,56.928001,57.191002,57.416000,57.618000,57.810001,58.000000,58.188000,58.362000,58.220001,58.071999
...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,51.629659,51.185245,50.864398,51.698867,51.559410,51.260341,51.521785,51.721148,52.035162,52.052128,52.059513
235,Timor-Leste,27.209000,26.469000,26.180000,25.913000,25.681000,25.450001,25.270000,25.160000,25.202000,25.034000,24.851000
236,Middle East & North Africa (IDA & IBRD countries),18.371887,18.220439,17.979422,17.871078,17.951179,17.612709,17.575307,18.002983,17.846133,17.801293,17.738633
237,Tonga,45.432999,45.334999,45.306999,45.316002,45.358002,45.323002,45.230000,45.244999,45.251999,45.250000,45.209999
238,South Asia (IDA & IBRD),27.832411,27.050263,26.050446,25.082699,25.354484,25.580315,25.875504,26.062319,26.460767,26.371171,26.278402
239,Sub-Saharan Africa (IDA & IBRD countries),61.260450,60.996748,60.923675,60.850175,60.929255,60.901829,61.045061,61.152641,61.363740,61.381375,61.395935
240,Trinidad and Tobago,51.660999,51.025002,50.359001,51.640999,51.896000,52.256001,50.848999,51.210999,50.511002,50.354000,50.147999
241,Tunisia,24.385000,24.459999,24.445999,25.245001,25.143000,24.933001,24.726999,24.468000,24.226000,24.080000,23.909000
242,Turkey,25.478001,27.033001,28.323000,28.879000,30.101999,30.243000,31.475000,32.507000,33.571999,33.520000,33.458000
243,Tuvalu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,Tanzania,84.781998,83.900002,82.952003,81.917000,80.780998,79.533997,79.553001,79.570000,79.577003,79.389000,79.203003
245,Uganda,65.688004,65.876999,66.081001,66.291000,66.430000,66.582001,66.744003,66.885002,67.037003,67.151001,67.269997
246,Ukraine,48.445000,48.410000,48.250999,47.485001,48.376999,47.040001,47.360001,47.075001,46.938000,46.679001,46.396999
247,Upper middle income,56.201803,55.670890,55.570200,55.603981,55.382775,55.061678,54.994629,54.828160,54.693724,54.296955,53.875677
248,Uruguay,55.616001,55.334000,55.978001,55.787998,54.973999,55.965000,55.724998,55.926998,55.597000,55.771000,55.931000
249,United States,58.144001,57.501999,56.930000,56.701000,56.292000,56.111000,55.834000,55.993999,56.313000,56.047001,55.778000
250,Uzbekistan,52.606998,52.736000,52.865002,52.997002,53.129002,53.244999,53.327999,53.377998,53.419998,53.412998,53.355999
251,St. Vincent and the Grenadines,56.441002,56.416000,56.487000,56.708000,56.938999,57.042999,57.071999,57.206001,57.195999,57.278999,57.313999
252,"Venezuela, RB",51.095001,50.619999,50.995998,50.584000,50.773998,50.542000,50.122002,48.775002,47.694000,47.743000,47.783001
253,British Virgin Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Virgin Islands (U.S.),58.008999,57.865002,57.429001,56.706001,56.375999,56.105999,55.855000,55.743000,55.769001,55.617001,55.433998
255,Vietnam,71.398003,71.305000,71.459999,71.969002,72.902000,73.195000,72.945999,72.642998,72.697998,72.649002,72.541000
256,Vanuatu,61.069000,61.241001,61.323002,61.354000,61.379002,61.411999,61.584999,61.528000,61.484001,61.507999,61.533001
257,World,49.091606,48.677926,48.363017,48.164190,48.114513,48.033072,48.025554,48.027061,48.089157,47.883420,47.662671
258,Samoa,24.337999,24.301001,24.173000,24.118000,24.091000,24.011999,23.916000,23.799000,23.740000,23.674999,23.587999
259,Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,"Yemen, Rep.",10.798000,10.049000,8.848000,7.799000,6.884000,6.083000,6.106000,6.117000,6.138000,5.983000,5.827000
261,South Africa,46.286999,44.728001,45.198002,45.418999,46.387001,46.612000,47.801998,47.797001,48.922001,48.848999,48.768002
262,Zambia,71.610001,71.059998,70.542999,70.021004,70.155998,70.295998,70.445000,70.585999,70.733002,70.752998,70.785004
263,Zimbabwe,77.295998,77.362000,77.492996,77.649002,77.796997,77.935997,78.069000,78.219002,78.387001,78.568001,78.733002

In [3]:
dfa1 =dfa.dropna(axis=0,how='any') 
dfa1

,country,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
1,Afghanistan,42.709000,42.735001,43.327999,44.117001,45.039001,46.016998,47.000999,47.765999,48.473999,48.660000,48.848999
2,Angola,75.255997,75.306999,75.344002,75.389000,75.432999,75.464996,75.478996,75.470001,75.450996,75.412003,75.372002
3,Albania,44.945000,45.693001,47.104000,48.806000,44.650002,44.789001,47.675999,47.459000,47.312000,47.191002,47.081001
5,Arab World,20.052651,20.169026,20.268955,20.453085,20.753035,20.686165,20.492409,20.589288,20.536024,20.537448,20.525228
6,United Arab Emirates,42.514999,44.028999,45.143002,46.213001,47.263000,48.323002,49.396000,50.161999,51.266998,51.148998,51.067001
7,Argentina,48.823002,47.833000,48.102001,48.188000,47.790001,47.157001,47.825001,48.480000,49.118000,48.966999,48.813999
8,Armenia,48.299000,49.587002,52.091999,51.969002,52.631001,51.946999,51.166000,49.441002,49.419998,49.575001,49.674000
11,Australia,58.821999,58.706001,58.952000,58.826000,58.707001,58.648998,59.066002,59.247002,59.693001,59.645000,59.591000
12,Austria,53.373001,53.507000,53.839001,54.337002,54.598999,54.562000,54.535999,54.945999,54.868999,54.826000,54.745998
13,Azerbaijan,59.617001,60.223000,60.813999,61.104000,61.323002,61.923000,62.516998,62.963001,63.262001,63.112999,62.916000
14,Burundi,80.610001,80.349998,80.112000,79.917999,79.748001,79.573998,79.844002,80.079002,80.286003,80.348999,80.363998
15,Belgium,46.745998,47.488998,46.805000,46.889000,47.594002,48.011002,48.023998,47.765999,47.891998,47.889000,47.867001
16,Benin,68.933998,69.223999,68.088997,68.207001,68.351997,68.512001,68.680000,68.835999,69.016998,69.176002,69.334999
17,Burkina Faso,60.092999,59.717999,59.341000,58.971001,58.606998,58.249001,58.375999,58.497002,58.626999,58.462002,58.292000
18,Bangladesh,29.382000,29.882999,30.371000,30.864000,31.364000,31.871000,32.383999,32.889999,35.852001,35.999001,36.143002
19,Bulgaria,48.089001,47.698002,47.216999,47.825001,48.528000,48.629002,48.632999,47.764999,49.626999,49.529999,49.416000
20,Bahrain,42.604000,43.763000,43.004002,43.202999,43.404999,43.615002,43.800999,44.011002,44.352001,44.473000,44.612999
21,"Bahamas, The",68.639999,68.742996,68.555000,68.616997,68.436996,68.180000,67.744003,67.530998,67.527000,67.568001,67.540001
22,Bosnia and Herzegovina,37.223999,37.063999,36.837002,36.547001,36.273998,35.972000,35.667000,35.258999,35.726002,35.627998,35.521000
23,Belarus,57.152000,57.540001,57.861000,58.136002,58.358002,58.527000,58.641998,58.665001,58.395000,58.126999,57.827000
24,Belize,50.747002,51.938000,53.235001,54.527000,53.701000,52.930000,52.212002,52.768002,52.924999,53.280998,53.648998
26,Bolivia,62.367001,62.019001,61.651001,57.944000,58.820999,60.900002,54.508999,60.321999,56.585999,56.595001,56.611000
27,Brazil,54.966000,53.576000,52.173000,53.077999,52.976002,52.860001,53.377998,53.320999,54.167999,54.029999,53.882000
28,Barbados,63.606998,63.492001,63.287998,62.061001,63.230999,61.855999,61.860001,62.568001,62.234001,61.894001,61.528000
29,Brunei Darussalam,56.659000,56.928001,57.191002,57.416000,57.618000,57.810001,58.000000,58.188000,58.362000,58.220001,58.071999
30,Bhutan,67.111000,64.556999,62.270000,63.502998,58.187000,54.931000,57.764999,57.895000,57.979000,58.202999,58.389000
31,Botswana,56.265999,53.546001,57.425999,61.106998,64.554001,64.907997,65.231003,65.524002,65.836998,66.192001,66.519997
32,Central African Republic,65.655998,65.663002,65.505997,65.321999,65.056000,64.838997,64.625000,64.691002,64.791000,64.723999,64.667000
33,Canada,61.874001,61.858002,61.601002,61.612000,61.683998,61.087002,60.770000,60.806999,61.015999,60.846001,60.658001
34,Central Europe and the Baltics,47.557086,47.988688,47.890527,48.313518,48.408511,48.811783,48.818785,48.807143,49.423060,49.226387,49.018014
...,...,...,...,...,...,...,...,...,...,...,...,...
231,Thailand,64.795998,63.848999,65.963997,65.171997,62.443001,61.446999,60.957001,60.061001,59.761002,59.465000,59.150002
232,Tajikistan,29.667999,29.502001,29.261000,28.990999,28.712999,28.476000,28.291000,28.084999,27.886999,27.794001,27.684999
233,Turkmenistan,52.314999,52.418999,52.530998,52.680000,52.830002,52.938999,52.994999,52.986000,52.926998,52.789001,52.633999
234,Latin America & the Caribbean (IDA & IBRD coun...,51.629659,51.185245,50.864398,51.698867,51.559410,51.260341,51.521785,51.721148,52.035162,52.052128,52.059513
235,Timor-Leste,27.209000,26.469000,26.180000,25.913000,25.681000,25.450001,25.270000,25.160000,25.202000,25.034000,24.851000
236,Middle East & North Africa (IDA & IBRD countries),18.371887,18.220439,17.979422,17.871078,17.951179,17.612709,17.575307,18.002983,17.846133,17.801293,17.738633
237,Tonga,45.432999,45.334999,45.306999,45.316002,45.358002,45.323002,45.230000,45.244999,45.251999,45.250000,45.209999
238,South Asia (IDA & IBRD),27.832411,27.050263,26.050446,25.082699,25.354484,25.580315,25.875504,26.062319,26.460767,26.371171,26.278402
239,Sub-Saharan Africa (IDA & IBRD countries),61.260450,60.996748,60.923675,60.850175,60.929255,60.901829,61.045061,61.152641,61.363740,61.381375,61.395935
240,Trinidad and Tobago,51.660999,51.025002,50.359001,51.640999,51.896000,52.256001,50.848999,51.210999,50.511002,50.354000,50.147999
241,Tunisia,24.385000,24.459999,24.445999,25.245001,25.143000,24.933001,24.726999,24.468000,24.226000,24.080000,23.909000
242,Turkey,25.478001,27.033001,28.323000,28.879000,30.101999,30.243000,31.475000,32.507000,33.571999,33.520000,33.458000
244,Tanzania,84.781998,83.900002,82.952003,81.917000,80.780998,79.533997,79.553001,79.570000,79.577003,79.389000,79.203003
245,Uganda,65.688004,65.876999,66.081001,66.291000,66.430000,66.582001,66.744003,66.885002,67.037003,67.151001,67.269997
246,Ukraine,48.445000,48.410000,48.250999,47.485001,48.376999,47.040001,47.360001,47.075001,46.938000,46.679001,46.396999
247,Upper middle income,56.201803,55.670890,55.570200,55.603981,55.382775,55.061678,54.994629,54.828160,54.693724,54.296955,53.875677
248,Uruguay,55.616001,55.334000,55.978001,55.787998,54.973999,55.965000,55.724998,55.926998,55.597000,55.771000,55.931000
249,United States,58.144001,57.501999,56.930000,56.701000,56.292000,56.111000,55.834000,55.993999,56.313000,56.047001,55.778000
250,Uzbekistan,52.606998,52.736000,52.865002,52.997002,53.129002,53.244999,53.327999,53.377998,53.419998,53.412998,53.355999
251,St. Vincent and the Grenadines,56.441002,56.416000,56.487000,56.708000,56.938999,57.042999,57.071999,57.206001,57.195999,57.278999,57.313999
252,"Venezuela, RB",51.095001,50.619999,50.995998,50.584000,50.773998,50.542000,50.122002,48.775002,47.694000,47.743000,47.783001
254,Virgin Islands (U.S.),58.008999,57.865002,57.429001,56.706001,56.375999,56.105999,55.855000,55.743000,55.769001,55.617001,55.433998
255,Vietnam,71.398003,71.305000,71.459999,71.969002,72.902000,73.195000,72.945999,72.642998,72.697998,72.649002,72.541000
256,Vanuatu,61.069000,61.241001,61.323002,61.354000,61.379002,61.411999,61.584999,61.528000,61.484001,61.507999,61.533001
257,World,49.091606,48.677926,48.363017,48.164190,48.114513,48.033072,48.025554,48.027061,48.089157,47.883420,47.662671
258,Samoa,24.337999,24.301001,24.173000,24.118000,24.091000,24.011999,23.916000,23.799000,23.740000,23.674999,23.587999
260,"Yemen, Rep.",10.798000,10.049000,8.848000,7.799000,6.884000,6.083000,6.106000,6.117000,6.138000,5.983000,5.827000
261,South Africa,46.286999,44.728001,45.198002,45.418999,46.387001,46.612000,47.801998,47.797001,48.922001,48.848999,48.768002
262,Zambia,71.610001,71.059998,70.542999,70.021004,70.155998,70.295998,70.445000,70.585999,70.733002,70.752998,70.785004
263,Zimbabwe,77.295998,77.362000,77.492996,77.649002,77.796997,77.935997,78.069000,78.219002,78.387001,78.568001,78.733002

In [4]:
dfa2=print(list(dfa1.country))
dfa2

['Afghanistan', 'Angola', 'Albania', 'Arab World', 'United Arab Emirates', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Burundi', 'Belgium', 'Benin', 'Burkina Faso', 'Bangladesh', 'Bulgaria', 'Bahrain', 'Bahamas, The', 'Bosnia and Herzegovina', 'Belarus', 'Belize', 'Bolivia', 'Brazil', 'Barbados', 'Brunei Darussalam', 'Bhutan', 'Botswana', 'Central African Republic', 'Canada', 'Central Europe and the Baltics', 'Switzerland', 'Channel Islands', 'Chile', 'China', "Cote d'Ivoire", 'Cameroon', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Colombia', 'Comoros', 'Cabo Verde', 'Costa Rica', 'Caribbean small states', 'Cuba', 'Cyprus', 'Czech Republic', 'Germany', 'Djibouti', 'Denmark', 'Dominican Republic', 'Algeria', 'East Asia & Pacific (excluding high income)', 'Early-demographic dividend', 'East Asia & Pacific', 'Europe & Central Asia (excluding high income)', 'Europe & Central Asia', 'Ecuador', 'Egypt, Arab Rep.', 'Euro area', 'Eritrea', 'Spain', 'Estonia', 'Ethiopia', 'European Union', 'Fragile and conflict affected situations', 'Finland', 'Fiji', 'France', 'Gabon', 'United Kingdom', 'Georgia', 'Ghana', 'Guinea', 'Gambia, The', 'Guinea-Bissau', 'Equatorial Guinea', 'Greece', 'Guatemala', 'Guam', 'Guyana', 'High income', 'Hong Kong SAR, China', 'Honduras', 'Heavily indebted poor countries (HIPC)', 'Croatia', 'Haiti', 'Hungary', 'IBRD only', 'IDA & IBRD total', 'IDA total', 'IDA blend', 'Indonesia', 'IDA only', 'India', 'Ireland', 'Iran, Islamic Rep.', 'Iraq', 'Iceland', 'Israel', 'Italy', 'Jamaica', 'Jordan', 'Japan', 'Kazakhstan', 'Kenya', 'Kyrgyz Republic', 'Cambodia', 'Korea, Rep.', 'Kuwait', 'Latin America & Caribbean (excluding high income)', 'Lao PDR', 'Lebanon', 'Liberia', 'Libya', 'St. Lucia', 'Latin America & Caribbean', 'Least developed countries: UN classification', 'Low income', 'Sri Lanka', 'Lower middle income', 'Low & middle income', 'Lesotho', 'Late-demographic dividend', 'Lithuania', 'Luxembourg', 'Latvia', 'Macao SAR, China', 'Morocco', 'Moldova', 'Madagascar', 'Maldives', 'Middle East & North Africa', 'Mexico', 'Middle income', 'North Macedonia', 'Mali', 'Malta', 'Myanmar', 'Middle East & North Africa (excluding high income)', 'Montenegro', 'Mongolia', 'Mozambique', 'Mauritania', 'Mauritius', 'Malawi', 'Malaysia', 'North America', 'Namibia', 'New Caledonia', 'Niger', 'Nigeria', 'Nicaragua', 'Netherlands', 'Norway', 'Nepal', 'New Zealand', 'OECD members', 'Oman', 'Other small states', 'Pakistan', 'Panama', 'Peru', 'Philippines', 'Papua New Guinea', 'Poland', 'Pre-demographic dividend', 'Puerto Rico', 'Korea, Dem. People鈥檚 Rep.', 'Portugal', 'Paraguay', 'West Bank and Gaza', 'Pacific island small states', 'Post-demographic dividend', 'French Polynesia', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'South Asia', 'Saudi Arabia', 'Sudan', 'Senegal', 'Singapore', 'Solomon Islands', 'Sierra Leone', 'El Salvador', 'Somalia', 'Serbia', 'Sub-Saharan Africa (excluding high income)', 'South Sudan', 'Sub-Saharan Africa', 'Small states', 'Sao Tome and Principe', 'Suriname', 'Slovak Republic', 'Slovenia', 'Sweden', 'Eswatini', 'Syrian Arab Republic', 'Chad', 'East Asia & Pacific (IDA & IBRD countries)', 'Europe & Central Asia (IDA & IBRD countries)', 'Togo', 'Thailand', 'Tajikistan', 'Turkmenistan', 'Latin America & the Caribbean (IDA & IBRD countries)', 'Timor-Leste', 'Middle East & North Africa (IDA & IBRD countries)', 'Tonga', 'South Asia (IDA & IBRD)', 'Sub-Saharan Africa (IDA & IBRD countries)', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Tanzania', 'Uganda', 'Ukraine', 'Upper middle income', 'Uruguay', 'United States', 'Uzbekistan', 'St. Vincent and the Grenadines', 'Venezuela, RB', 'Virgin Islands (U.S.)', 'Vietnam', 'Vanuatu', 'World', 'Samoa', 'Yemen, Rep.', 'South Africa', 'Zambia', 'Zimbabwe']

In [5]:
x轴 = [int(x)for x in dfa.columns.values[-11:]]
x轴

[2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]

In [6]:
中国=list(dfa.loc['China'].values)[-11:]
中国

KeyError: 'the label [China] is not in the [index]'

In [ ]:
加拿大=list(dfa.loc['Canada'].values)[-11:]
加拿大

In [7]:
法国=list(df.loc['France'].values)[-11:]
法国

NameError: name 'df' is not defined

In [8]:

from pyecharts import options as opts
from pyecharts.charts import Bar


def bar_base() -> Bar:
    c = (
        Bar()
        .add_xaxis(x轴)
        .add_yaxis("中", 中国)
        .add_yaxis("加", 加拿大)
        .add_yaxis("法", 法国)
        .set_global_opts(title_opts=opts.TitleOpts(title="男性劳动力参与率", subtitle="3个国家"))
    )
    return c
bar_base().render_notebook()

NameError: name '中国' is not defined

In [ ]:

from pyecharts import options as opts
from pyecharts.charts import Bar


def bar_base() -> Bar:
    c = (
        Bar()
        .add_xaxis(x轴)
        .add_yaxis(
            "country",
            dfa2,
            markpoint_opts=opts.MarkPointOpts(data=[opts.MarkPointItem(type_="min")]),
        )
        .set_global_opts(title_opts=opts.TitleOpts(title="男性劳动力参与率"))
    )
    return c
bar_base().render_notebook()

In [10]:
df1 = pd.read_csv("School_enrollment.csv",encoding = 'gbk')
df1

,country,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,1.43284,1.41237,1.49926,1.49460,2.20461,2.27028,2.26241,1.94031,NaN,NaN,NaN
1,Afghanistan,0.23639,NaN,0.34565,NaN,NaN,0.27600,NaN,NaN,NaN,0.34523,NaN
2,Angola,NaN,NaN,0.36925,NaN,0.79661,NaN,0.78541,0.82566,NaN,NaN,NaN
3,Albania,1.36375,1.35543,1.37539,1.39701,1.40728,1.43551,1.42608,1.47336,1.52645,1.56984,NaN
4,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Arab World,1.04094,1.04136,1.04497,1.03854,1.03392,1.03775,1.06004,1.08843,1.07958,1.10959,NaN
6,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Argentina,1.49186,1.49160,1.54854,1.56222,1.60015,1.61270,1.63170,1.65707,1.66431,NaN,NaN
8,Armenia,1.23839,1.21927,1.18578,1.18178,1.13286,1.14013,1.19169,1.26878,1.27369,1.32958,NaN
9,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Antigua and Barbuda,2.27844,2.68089,2.07896,2.24567,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Australia,NaN,NaN,NaN,NaN,NaN,NaN,1.44446,1.42971,1.42093,NaN,NaN
12,Austria,NaN,NaN,NaN,NaN,1.19662,1.19258,1.19299,1.18812,1.18463,NaN,NaN
13,Azerbaijan,0.98681,0.98937,1.01629,1.04769,1.11285,1.14195,1.16234,1.17749,1.14894,1.14603,NaN
14,Burundi,NaN,0.54268,0.46166,0.48504,0.44494,0.32848,NaN,0.42868,0.44861,NaN,NaN
15,Belgium,1.24892,1.26628,1.27115,1.28248,1.29505,1.30332,1.30720,1.30150,1.30557,NaN,NaN
16,Benin,0.39077,0.35390,0.27232,0.34509,0.38012,0.36512,0.40193,0.42069,0.43936,NaN,NaN
17,Burkina Faso,0.48354,0.47905,0.49631,0.49568,0.49261,0.48590,0.52272,0.51226,0.52122,0.58203,NaN
18,Bangladesh,0.59971,NaN,0.69404,0.72256,NaN,0.73733,NaN,0.70066,0.70081,0.70714,NaN
19,Bulgaria,1.32993,1.32290,1.29973,1.27459,1.27105,1.25935,1.27605,1.24473,NaN,NaN,NaN
20,Bahrain,NaN,NaN,1.71121,2.03262,2.23749,1.97832,1.91666,1.86808,1.89295,1.83390,NaN
21,"Bahamas, The",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Belarus,1.47214,1.44655,1.42699,1.39937,1.35478,1.33626,1.32835,1.29107,1.24343,1.18604,NaN
24,Belize,1.66270,1.59618,1.65815,1.65322,1.64151,1.65257,1.60790,1.61911,1.62002,NaN,NaN
25,Bermuda,2.52370,2.05683,2.06675,1.98982,2.22829,1.87512,2.31080,NaN,1.68152,1.49869,NaN
26,Bolivia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Brazil,1.32152,NaN,1.31336,1.34778,1.35137,1.36005,1.33980,1.38149,1.36569,NaN,NaN
28,Barbados,2.20390,2.18271,2.24550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Brunei Darussalam,1.78264,1.86650,1.76483,1.76696,1.85738,1.73538,1.70615,1.65575,1.62027,1.56193,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,1.26326,1.27645,1.27155,1.28637,1.28794,1.29219,1.28962,1.29674,1.29734,1.29563,NaN
235,Timor-Leste,0.68262,0.71834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,Middle East & North Africa (IDA & IBRD countries),1.00396,0.98703,1.00101,1.00010,0.97806,0.96614,0.97803,0.99614,0.99814,1.01615,NaN
237,Tonga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238,South Asia (IDA & IBRD),0.71430,0.73983,0.79237,0.87568,0.92636,0.96754,0.96198,0.96763,0.98945,1.01186,NaN
239,Sub-Saharan Africa (IDA & IBRD countries),0.70838,0.70587,0.69073,0.71461,0.72391,0.72271,0.73492,0.74392,0.75258,0.75471,NaN
240,Trinidad and Tobago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
241,Tunisia,1.50840,1.55235,1.63399,1.57185,1.59912,1.64585,1.65751,1.73072,1.80442,NaN,NaN
242,Turkey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,Tuvalu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,Tanzania,NaN,0.82463,NaN,0.54915,0.54125,NaN,0.53811,NaN,NaN,NaN,NaN
245,Uganda,0.75974,0.74625,0.73313,0.68457,NaN,0.72971,NaN,NaN,NaN,NaN,NaN
246,Ukraine,1.27167,1.25648,1.18348,1.15083,1.19260,1.15601,NaN,NaN,NaN,NaN,NaN
247,Upper middle income,1.15972,1.16757,1.17606,1.17781,1.17991,1.17814,1.18721,1.19392,1.19559,1.20171,NaN
248,Uruguay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,United States,1.40157,1.39311,1.38578,1.39345,1.37343,1.36078,1.35624,1.34487,1.36020,NaN,NaN
250,Uzbekistan,0.69056,0.68058,0.64384,0.59820,0.59647,0.62043,0.62901,0.64671,0.60792,0.69772,NaN
251,St. Vincent and the Grenadines,NaN,NaN,NaN,NaN,NaN,2.21255,1.67388,NaN,NaN,NaN,NaN
252,"Venezuela, RB",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
253,British Virgin Islands,1.59500,NaN,NaN,NaN,NaN,NaN,1.79420,1.58504,NaN,NaN,NaN
254,Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,Vietnam,1.00745,1.01665,1.02616,NaN,0.90818,1.05553,1.00551,1.24238,NaN,NaN,NaN
256,Vanuatu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,World,1.07637,1.07705,1.07587,1.09559,1.10652,1.11485,1.11687,1.12460,1.13128,1.13933,NaN
258,Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,"Yemen, Rep.",NaN,0.43666,0.44019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,South Africa,NaN,NaN,NaN,1.40606,1.41345,1.41181,NaN,1.40463,1.43187,NaN,NaN
262,Zambia,NaN,NaN,0.36901,0.73715,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,Zimbabwe,NaN,0.73304,0.69562,0.70526,0.77549,NaN,0.83997,NaN,NaN,NaN,NaN